Akademik_Personeller:
    - Ad: "Berkay"
      Soyad: "Fis"
      Ana_Bilim_Dali: "Bilgisayar Bilimleri"
      Unvan: "Prof Dr"
      Kisaltma: "BF"
      Kullanici_Adi: "bf"
      Sifre: "bfis"
      Koordinator_Mu: true
    - Ad: "Orhan"
      Soyad: "Pamuk"
      Ana_Bilim_Dali: "Bilgisayar Bilimleri"
      Unvan: "Prof Dr"
      Kisaltma: "OP"
      Kullanici_Adi: "op"
      Sifre: "opamuk"
Ogrenciler:
    - Ogrenci_No: "5001520"
      Ad: "Tarik"
      Soyad: "Sakrak"
    - Ogrenci_No: "5002530"
      Ad: "Mert"
      Soyad: "Kazanc"
AlanOturumlar:
    - Ad : "Ağ Teknolojileri, İşletim Sistemleri, Robot Teknolojileri "
    - Ad : "Doğal Dil İşleme, Yapay Zeka, Görüntü ve İşaret İşleme"
    - Ad : "Yazılım Müh., Büyük Veri İşleme, Veri Madenciliği"