Akademik_Personeller:
    - Ad: "Berkay"
      Soyad: "Fis"
      Ana_Bilim_Dali: "Bilgisayar Bilimleri"
      Unvan: "Prof Dr"
      Kisaltma: "BF"
      Kullanici_Adi: "bf"
      Sifre: "bfis"
    - Ad: "Orhan"
      Soyad: "Pamuk"
      Ana_Bilim_Dali: "Bilgisayar Bilimleri"
      Unvan: "Prof Dr"
      Kisaltma: "OP"
      Kullanici_Adi: "op"
      Sifre: "opamuk"
Ogrenciler:
    - Ogrenci_No: "5001520"
      Ad: "Tarik"
      Soyad: "Sakrak"
    - Ogrenci_No: "5002530"
      Ad: "Mert"
      Soyad: "Kazanc"